// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/swarm_controller/swarm_controller.proto)

#include <iomanip>

#include "swarm_controller_impl.h"
#include "plugins/swarm_controller/swarm_controller.h"

namespace mavsdk {




SwarmController::SwarmController(System& system) : PluginBase(), _impl{std::make_unique<SwarmControllerImpl>(system)} {}

SwarmController::SwarmController(std::shared_ptr<System> system) : PluginBase(), _impl{std::make_unique<SwarmControllerImpl>(system)} {}


SwarmController::~SwarmController() {}





bool SwarmController::start() const
{
    return _impl->start();
}





bool SwarmController::stop() const
{
    return _impl->stop();
}





bool SwarmController::is_active() const
{
    return _impl->is_active();
}





void SwarmController::set_rate() const
{
    _impl->set_rate();
}





bool SwarmController::set_position_global(PositionGlobalYaw position_global_yaw) const
{
    return _impl->set_position_global(position_global_yaw);
}





} // namespace mavsdk