// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/swarm_server/swarm_server.proto)

#pragma once

#include <array>
#include <cmath>
#include <functional>
#include <limits>
#include <memory>
#include <string>
#include <utility>
#include <vector>

#include "mavsdk/server_plugin_base.h"

namespace mavsdk {

class ServerComponent;
class SwarmServerImpl;

/**
 * @brief
 */
class SwarmServer : public ServerPluginBase {
public:
    /**
     * @brief Constructor. Creates the plugin for a ServerComponent instance.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto swarm_server = SwarmServer(server_component);
     *     ```
     *
     * @param server_component The ServerComponent instance associated with this server plugin.
     */
    explicit SwarmServer(std::shared_ptr<ServerComponent> server_component);

    /**
     * @brief Destructor (internal use only).
     */
    ~SwarmServer() override;

    /**
     * @brief Callback type for subscribe_position_target_global_setpoint.
     */

    using PositionTargetGlobalSetpointCallback = std::function<void(PositionGlobalYaw)>;

    /**
     * @brief
     */
    void subscribe_position_target_global_setpoint(PositionTargetGlobalSetpointCallback callback);

    /**
     * @brief Copy constructor.
     */
    SwarmServer(const SwarmServer& other);

    /**
     * @brief Equality operator (object is not copyable).
     */
    const SwarmServer& operator=(const SwarmServer&) = delete;

private:
    /** @private Underlying implementation, set at instantiation */
    std::unique_ptr<SwarmServerImpl> _impl;
};

} // namespace mavsdk