// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/swarm_server/swarm_server.proto)

#include <iomanip>

#include "swarm_server_impl.h"
#include "plugins/swarm_server/swarm_server.h"

namespace mavsdk {

SwarmServer::SwarmServer(std::shared_ptr<ServerComponent> server_component) :
    ServerPluginBase(),
    _impl{std::make_unique<SwarmServerImpl>(server_component)}
{}

SwarmServer::~SwarmServer() {}

void SwarmServer::subscribe_position_target_global_setpoint(
    PositionTargetGlobalSetpointCallback callback)
{
    _impl->subscribe_position_target_global_setpoint(callback);
}

} // namespace mavsdk